"""A stable entry point for Claude Code's statusLine setting.

The statusline is configured once, in Claude Code's settings, but a plugin
installed from GitHub lives under a directory whose name carries a content hash and
changes on every update. herdr's state directory does not, so the startup hook
writes a tiny launcher there: settings point at that fixed path forever and it is
rewritten to the current plugin root each time herdr starts.

The launcher also exports the state directory, so the statusline and the event
hooks share one cache no matter how the statusline was invoked.
"""

import os
import stat

NAME = "statusline"

TEMPLATE = """#!/bin/sh
# Generated by herdr-model-badge %(version)s. Rewritten on each herdr startup;
# edits here are lost. Point Claude Code's statusLine at this path:
#
#   "statusLine": { "type": "command", "command": "%(path)s /path/to/your/statusline" }
#
# Any arguments are the statusline command to wrap; its output passes through
# unchanged. With no arguments, nothing is printed.
HERDR_PLUGIN_STATE_DIR=%(state_dir)s
export HERDR_PLUGIN_STATE_DIR
PYTHONPATH=%(root)s${PYTHONPATH:+:$PYTHONPATH}
export PYTHONPATH
exec python3 -m herdr_model_badge statusline -- "$@"
"""


def path_for(state_dir):
    return os.path.join(state_dir, NAME)


def write(root, state_dir, version):
    """Write the launcher and make it executable. Returns its path, or ``None``."""
    target = path_for(state_dir)
    body = TEMPLATE % {
        "version": version,
        "path": target,
        "state_dir": _quote(state_dir),
        "root": _quote(root),
    }
    try:
        os.makedirs(state_dir, exist_ok=True)
        # Skip an identical rewrite so the file's mtime means something.
        if os.path.exists(target):
            with open(target, encoding="utf-8") as handle:
                if handle.read() == body:
                    return target
        temporary = target + ".tmp"
        with open(temporary, "w", encoding="utf-8") as handle:
            handle.write(body)
        os.chmod(temporary, os.stat(temporary).st_mode | stat.S_IXUSR)
        os.replace(temporary, target)
    except OSError:
        return None
    return target


def _quote(value):
    """Single-quote a path for /bin/sh, since a plugin root may contain spaces."""
    return "'%s'" % value.replace("'", "'\\''")
